import type { CampaignPrompt } from '../types/saga';

export const createCampaignPrompt = (
    id: number,
    name: string,
    createdAt: Date,
    updatedAt: Date,
    tone: 'heroic' | 'gritty' | 'dark' | 'lighthearted' | 'epic' | 'horror' | 'comedic' | 'mysterious' | 'romantic' | 'political',
    mood: 'hopeful' | 'grim' | 'whimsical' | 'tense' | 'melancholic' | 'triumphant' | 'foreboding' | 'nostalgic',
    maturityLevel: 'family-friendly' | 'teen' | 'mature' | 'adult',
    primaryThemes: string[],
    conflictTypes: ('personal' | 'political' | 'cosmic' | 'moral' | 'survival' | 'mystery')[],
    settingGenre: 'high-fantasy' | 'low-fantasy' | 'dark-fantasy' | 'urban-fantasy' | 'steampunk' | 'gothic' | 'mythic' | 'post-apocalyptic',
    magicPrevalence: 'rare' | 'uncommon' | 'common' | 'ubiquitous',
    technologyLevel: 'primitive' | 'medieval' | 'renaissance' | 'industrial' | 'modern' | 'futuristic',
    pacing: 'slow-burn' | 'steady' | 'fast-paced' | 'episodic' | 'milestone-driven',
    complexity: 'straightforward' | 'layered' | 'intricate' | 'labyrinthine',
    playerAgency: 'high' | 'medium' | 'guided' | 'on-rails',
    violenceLevel: 'minimal' | 'moderate' | 'realistic' | 'graphic',
    socialComplexity: 'simple' | 'moderate' | 'intricate' | 'byzantine',
    moralAmbiguity: 'clear' | 'nuanced' | 'gray' | 'subversive',
    keyWords: string[],
    rulesEmphasis: 'strict' | 'flexible' | 'narrative-first' | 'rule-of-cool',
    homebrewFriendly: boolean,
    description?: string,
    inspirationSources?: string[],
    avoidanceList?: string[],
): CampaignPrompt => ({
    id,
    name,
    description,
    createdAt,
    updatedAt,
    tone,
    mood,
    maturityLevel,
    primaryThemes,
    conflictTypes,
    settingGenre,
    magicPrevalence,
    technologyLevel,
    pacing,
    complexity,
    playerAgency,
    violenceLevel,
    socialComplexity,
    moralAmbiguity,
    keyWords,
    rulesEmphasis,
    homebrewFriendly,
    inspirationSources,
    avoidanceList
});