import type { Faction, NPC, Location } from '../types/saga';

export const createFaction = (
    id: number,
    name: string,
    createdAt: Date,
    updatedAt: Date,
    members: NPC[],
    locations: Location[],
    goals: string[],
    methods: string[],
    resources: string[],
    allies: Faction[],
    enemies: Faction[],
    status: 'growing' | 'stable' | 'declining' | 'hidden' | 'defunct',
    playerRelationship: 'allied' | 'friendly' | 'neutral' | 'unfriendly' | 'hostile' | 'unknown',
    description?: string,
    leader?: NPC,
    leaderId?: number,
    insignia?: string,
    hierarchy?: string,
): Faction => ({
    id,
    name,
    description,
    createdAt,
    updatedAt,
    members,
    locations,
    goals,
    methods,
    resources,
    allies,
    enemies,
    status,
    playerRelationship,
    leader,
    leaderId,
    insignia,
    hierarchy
});