import type { Location, NPC, PointOfInterest } from '../types/saga';

export const createLocation = (
    id: number,
    name: string,
    createdAt: Date,
    updatedAt: Date,
    type: 'continent' | 'region' | 'city' | 'town' | 'village' | 'dungeon' | 'wilderness' | 'building' | 'other',
    children: Location[],
    description?: string,
    parent?: Location,
    parentId?: number,
    government?: string,
    population?: number,
    races?: string[],
    economy?: string,
    defenses?: string,
    keyNPCs?: NPC[],
    pointsOfInterest?: PointOfInterest[],
    rumors?: string[],
    secrets?: string[],
    climate?: string,
    terrain?: string,
    history?: string,
): Location => ({
    id,
    name,
    description,
    createdAt,
    updatedAt,
    type,
    children,
    parent,
    parentId,
    government,
    population,
    races,
    economy,
    defenses,
    keyNPCs,
    pointsOfInterest,
    rumors,
    secrets,
    climate,
    terrain,
    history
});