import type { NPC, Location, Faction, Session, Item, NPCRelationship } from '../types/saga';

export const createNPC = (
    id: number,
    name: string,
    createdAt: Date,
    updatedAt: Date,
    type: 'individual' | 'group',
    occupation: string,
    appearance: string,
    personality: string,
    motivation: string,
    status: 'alive' | 'deceased' | 'unknown',
    importance: 'background' | 'minor' | 'major' | 'villain' | 'ally',
    isUnique: boolean,
    relationships: NPCRelationship[],
    description?: string,
    race?: string,
    klass?: string,
    goals?: string[],
    secrets?: string[],
    location?: Location,
    locationId?: number,
    faction?: Faction,
    factionId?: number,
    firstAppearance?: Session,
    firstAppearanceId?: number,
    voice?: string,
    mannerisms?: string[],
    inventory?: Item[],
    quotes?: string[],
): NPC => ({
    id,
    name,
    description,
    createdAt,
    updatedAt,
    type,
    race,
    klass,
    occupation,
    appearance,
    personality,
    motivation,
    goals,
    secrets,
    relationships,
    location,
    locationId,
    faction,
    factionId,
    status,
    importance,
    firstAppearance,
    firstAppearanceId,
    voice,
    mannerisms,
    inventory,
    quotes,
    isUnique
});