import type { Part, Campaign, Session, NPC, Location } from '../types/saga';

export const createPart = (
    id: number,
    name: string,
    createdAt: Date,
    updatedAt: Date,
    campaign: Campaign,
    campaignId: number,
    summary: string,
    status: 'planned' | 'active' | 'completed' | 'abandoned',
    sessions: Session[],
    mainNPCs: NPC[],
    keyLocations: Location[],
    order: number,
    description?: string,
    plotTwists?: string[],
    climax?: string,
    resolution?: string,
    nextPart?: Part,
    nextPartId?: number,
    previousPart?: Part,
    previousPartId?: number,
): Part => ({
    id,
    name,
    description,
    createdAt,
    updatedAt,
    campaign,
    campaignId,
    summary,
    status,
    sessions,
    mainNPCs,
    keyLocations,
    order,
    plotTwists,
    climax,
    resolution,
    nextPart,
    nextPartId,
    previousPart,
    previousPartId
});