import type { Session, Part, SessionPlan, SessionSummary, Location, NPC } from '../types/saga';

export const createSession = (
    id: number,
    name: string,
    createdAt: Date,
    updatedAt: Date,
    part: Part,
    partId: number,
    number: number,
    locations: Location[],
    npcs: NPC[],
    description?: string,
    date?: Date,
    duration?: number,
    plan?: SessionPlan,
    summary?: SessionSummary,
    discoveries?: string[],
    nextSession?: Session,
    nextSessionId?: number,
): Session => ({
    id,
    name,
    description,
    createdAt,
    updatedAt,
    part,
    partId,
    number,
    locations,
    npcs,
    date,
    duration,
    plan,
    summary,
    discoveries,
    nextSession,
    nextSessionId
});